/*----- PROTECTED REGION ID(VacuumGuageStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        VacuumGuageStateMachine.cpp
//
// description : State machine file for the VacuumGuage class
//
// project :     Prevac training
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <VacuumGuage.h>

/*----- PROTECTED REGION END -----*/	//	VacuumGuage::VacuumGuageStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  The guage is On
//  OFF     |  The guage is off


namespace VacuumGuage_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::is_Pressure_allowed()
 *	Description : Execution allowed for Pressure attribute
 */
//--------------------------------------------------------
bool VacuumGuage::is_Pressure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Pressure attribute in read access.
	/*----- PROTECTED REGION ID(VacuumGuage::PressureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::PressureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::is_SimulatedPressureValue_allowed()
 *	Description : Execution allowed for SimulatedPressureValue attribute
 */
//--------------------------------------------------------
bool VacuumGuage::is_SimulatedPressureValue_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SimulatedPressureValue attribute in Write access.
	/*----- PROTECTED REGION ID(VacuumGuage::SimulatedPressureValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::SimulatedPressureValueStateAllowed_WRITE

	//	Not any excluded states for SimulatedPressureValue attribute in read access.
	/*----- PROTECTED REGION ID(VacuumGuage::SimulatedPressureValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::SimulatedPressureValueStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool VacuumGuage::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(VacuumGuage::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool VacuumGuage::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(VacuumGuage::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::OffStateAllowed
	return true;
}

}	//	End of namespace
