/*----- PROTECTED REGION ID(VacuumGuage.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        VacuumGuage.cpp
//
// description : C++ source for the VacuumGuage class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               VacuumGuage are implemented in this file.
//
// project :     Prevac training
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <VacuumGuage.h>
#include <VacuumGuageClass.h>

/*----- PROTECTED REGION END -----*/	//	VacuumGuage.cpp

/**
 *  VacuumGuage class description:
 *    
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  On            |  on
//  Off           |  off
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Pressure                |  Tango::DevDouble	Scalar
//  SimulatedPressureValue  |  Tango::DevDouble	Scalar
//================================================================

namespace VacuumGuage_ns
{
/*----- PROTECTED REGION ID(VacuumGuage::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	VacuumGuage::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::VacuumGuage()
 *	Description : Constructors for a Tango device
 *                implementing the classVacuumGuage
 */
//--------------------------------------------------------
VacuumGuage::VacuumGuage(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(VacuumGuage::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::constructor_1
}
//--------------------------------------------------------
VacuumGuage::VacuumGuage(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(VacuumGuage::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::constructor_2
}
//--------------------------------------------------------
VacuumGuage::VacuumGuage(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(VacuumGuage::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void VacuumGuage::delete_device()
{
	DEBUG_STREAM << "VacuumGuage::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::delete_device
	delete[] attr_Pressure_read;
	delete[] attr_SimulatedPressureValue_read;
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void VacuumGuage::init_device()
{
	DEBUG_STREAM << "VacuumGuage::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::init_device_before
	
	//	No device property to be read from database
	
	attr_Pressure_read = new Tango::DevDouble[1];
	attr_SimulatedPressureValue_read = new Tango::DevDouble[1];

	/*----- PROTECTED REGION ID(VacuumGuage::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::init_device
}


//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void VacuumGuage::always_executed_hook()
{
	INFO_STREAM << "VacuumGuage::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void VacuumGuage::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "VacuumGuage::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void VacuumGuage::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "VacuumGuage::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Pressure related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void VacuumGuage::read_Pressure(Tango::Attribute &attr)
{
	DEBUG_STREAM << "VacuumGuage::read_Pressure(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::read_Pressure) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_Pressure_read);
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::read_Pressure
}
//--------------------------------------------------------
/**
 *	Read attribute SimulatedPressureValue related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void VacuumGuage::read_SimulatedPressureValue(Tango::Attribute &attr)
{
	DEBUG_STREAM << "VacuumGuage::read_SimulatedPressureValue(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::read_SimulatedPressureValue) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_SimulatedPressureValue_read);
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::read_SimulatedPressureValue
}
//--------------------------------------------------------
/**
 *	Write attribute SimulatedPressureValue related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void VacuumGuage::write_SimulatedPressureValue(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "VacuumGuage::write_SimulatedPressureValue(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(VacuumGuage::write_SimulatedPressureValue) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::write_SimulatedPressureValue
}

//--------------------------------------------------------
/**
 *	Method      : VacuumGuage::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void VacuumGuage::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(VacuumGuage::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command On related method
 *	Description: Switch the guage one
 *
 */
//--------------------------------------------------------
void VacuumGuage::on()
{
	DEBUG_STREAM << "VacuumGuage::On()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::on) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::on
}
//--------------------------------------------------------
/**
 *	Command Off related method
 *	Description: Switch the guage off
 *
 */
//--------------------------------------------------------
void VacuumGuage::off()
{
	DEBUG_STREAM << "VacuumGuage::Off()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(VacuumGuage::off) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuage::off
}

/*----- PROTECTED REGION ID(VacuumGuage::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	VacuumGuage::namespace_ending
} //	namespace
