/*----- PROTECTED REGION ID(VacuumGuageClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        VacuumGuageClass.h
//
// description : Include for the VacuumGuage root class.
//               This class is the singleton class for
//                the VacuumGuage device class.
//               It contains all properties and methods which the 
//               VacuumGuage requires only once e.g. the commands.
//
// project :     Prevac training
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef VacuumGuageClass_H
#define VacuumGuageClass_H

#include <tango.h>
#include <VacuumGuage.h>


/*----- PROTECTED REGION END -----*/	//	VacuumGuageClass.h


namespace VacuumGuage_ns
{
/*----- PROTECTED REGION ID(VacuumGuageClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	VacuumGuageClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Pressure class definition
class PressureAttrib: public Tango::Attr
{
public:
	PressureAttrib():Attr("Pressure",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~PressureAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<VacuumGuage *>(dev))->read_Pressure(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<VacuumGuage *>(dev))->is_Pressure_allowed(ty);}
};

//	Attribute SimulatedPressureValue class definition
class SimulatedPressureValueAttrib: public Tango::Attr
{
public:
	SimulatedPressureValueAttrib():Attr("SimulatedPressureValue",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~SimulatedPressureValueAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<VacuumGuage *>(dev))->read_SimulatedPressureValue(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<VacuumGuage *>(dev))->write_SimulatedPressureValue(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<VacuumGuage *>(dev))->is_SimulatedPressureValue_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command On class definition
class OnClass : public Tango::Command
{
public:
	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<VacuumGuage *>(dev))->is_On_allowed(any);}
};

//	Command Off class definition
class OffClass : public Tango::Command
{
public:
	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	OffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~OffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<VacuumGuage *>(dev))->is_Off_allowed(any);}
};


/**
 *	The VacuumGuageClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  VacuumGuageClass : public Tango::DeviceClass
#else
class VacuumGuageClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(VacuumGuageClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	VacuumGuageClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static VacuumGuageClass *init(const char *);
		static VacuumGuageClass *instance();
		~VacuumGuageClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		VacuumGuageClass(string &);
		static VacuumGuageClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	VacuumGuage_H
